# Generated by Django 6.0 on 2026-01-08 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grade', '0001_initial'),
        ('submission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='submission.submission'),
        ),
    ]
